name: Deploy React App to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - run: |
        npm install
        npm run build

    - name: Upload dist folder to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "dist"
        target: "~/ec2-deploy-test"

    - name: Restart PM2 on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          mkdir -p ~/ec2-deploy-test
          cd ~/ec2-deploy-test
          pm2 delete react-app || true
          pm2 start serve --name "react-app" -- -s dist -l 3000
          pm2 save
